In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
dataset = pd.read_csv("Iris.csv")

In [ ]:
dataset

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Species = le.fit_transform(dataset["Species"])
dataset["Species"] = Species

In [ ]:
dataset = np.array(dataset)
rows, cols = dataset.shape
np.random.shuffle(dataset)

training_data = dataset[:int(0.8*rows)]
rows1, cols1 = training_data.shape
training_data = training_data.T

X_train = training_data[1:cols1-1]
Y_train = training_data[cols1-1]

testing_data = dataset[int(0.8*rows):]
rows2, cols2 = testing_data.shape
testing_data = testing_data.T

X_test = testing_data[1:cols2-1]
Y_test = testing_data[cols2-1]

In [ ]:
training_data

array([[1.11e+02, 7.10e+01, 8.40e+01, 6.70e+01, 1.12e+02, 9.00e+00,
        2.10e+01, 6.20e+01, 9.40e+01, 1.24e+02, 3.90e+01, 4.90e+01,
        5.10e+01, 1.39e+02, 5.20e+01, 8.50e+01, 5.00e+00, 6.90e+01,
        1.33e+02, 8.30e+01, 5.50e+01, 3.20e+01, 5.40e+01, 1.70e+01,
        1.49e+02, 3.80e+01, 1.16e+02, 1.28e+02, 5.70e+01, 1.00e+00,
        1.40e+02, 7.20e+01, 1.48e+02, 1.10e+01, 8.20e+01, 9.70e+01,
        8.80e+01, 1.14e+02, 9.20e+01, 9.60e+01, 1.43e+02, 2.40e+01,
        1.21e+02, 9.80e+01, 1.19e+02, 1.00e+01, 8.10e+01, 3.00e+00,
        1.05e+02, 6.50e+01, 1.90e+01, 1.32e+02, 1.22e+02, 9.50e+01,
        1.31e+02, 1.01e+02, 8.70e+01, 3.40e+01, 1.41e+02, 4.00e+01,
        7.80e+01, 6.30e+01, 5.00e+01, 1.44e+02, 1.30e+01, 5.60e+01,
        1.50e+01, 8.90e+01, 2.90e+01, 1.27e+02, 2.60e+01, 4.70e+01,
        1.03e+02, 1.10e+02, 2.30e+01, 1.40e+01, 1.02e+02, 8.00e+00,
        3.50e+01, 1.46e+02, 6.80e+01, 7.90e+01, 1.07e+02, 1.26e+02,
        1.34e+02, 5.30e+01, 4.40e+01, 2.00e+00, 

In [ ]:
testing_data

array([[ 64. , 109. , 145. ,  27. ,  80. , 138. , 125. ,   7. , 106. ,
        135. ,  20. ,   4. ,  61. , 104. ,  18. , 120. ,  74. ,  22. ,
         42. ,  73. ,  59. ,  16. ,  86. , 123. ,  91. , 150. ,  58. ,
        142. ,  30. ,  76. ],
       [  6.1,   6.7,   6.7,   5. ,   5.7,   6.4,   6.7,   4.6,   7.6,
          6.1,   5.1,   4.6,   5. ,   6.3,   5.1,   6. ,   6.1,   5.1,
          4.5,   6.3,   6.6,   5.7,   6. ,   7.7,   5.5,   5.9,   4.9,
          6.9,   4.7,   6.6],
       [  2.9,   2.5,   3.3,   3.4,   2.6,   3.1,   3.3,   3.4,   3. ,
          2.6,   3.8,   3.1,   2. ,   2.9,   3.5,   2.2,   2.8,   3.7,
          2.3,   2.5,   2.9,   4.4,   3.4,   2.8,   2.6,   3. ,   2.4,
          3.1,   3.2,   3. ],
       [  4.7,   5.8,   5.7,   1.6,   3.5,   5.5,   5.7,   1.4,   6.6,
          5.6,   1.5,   1.5,   3.5,   5.6,   1.4,   5. ,   4.7,   1.5,
          1.3,   4.9,   4.6,   1.5,   4.5,   6.7,   4.4,   5.1,   3.3,
          5.1,   1.6,   4.4],
       [  1.4,   1.8,   2.5,

In [ ]:
X_train

array([[6.5, 5.9, 6. , 5.6, 6.4, 4.4, 5.4, 5.9, 5. , 6.3, 4.4, 5.3, 7. ,
        6. , 6.4, 5.4, 5. , 6.2, 6.4, 5.8, 6.5, 5.4, 5.5, 5.4, 6.2, 4.9,
        6.4, 6.1, 6.3, 5.1, 6.9, 6.1, 6.5, 5.4, 5.5, 5.7, 6.3, 5.7, 6.1,
        5.7, 5.8, 5.1, 6.9, 6.2, 7.7, 4.9, 5.5, 4.7, 6.5, 5.6, 5.7, 7.9,
        5.6, 5.6, 7.4, 6.3, 6.7, 5.5, 6.7, 5.1, 6.7, 6. , 5. , 6.8, 4.8,
        5.7, 5.8, 5.6, 5.2, 6.2, 5. , 5.1, 7.1, 7.2, 4.6, 4.3, 5.8, 5. ,
        4.9, 6.7, 5.8, 6. , 4.9, 7.2, 6.3, 6.9, 5. , 4.9, 7.3, 5.8, 4.8,
        4.8, 5.1, 4.6, 4.4, 5.2, 6.3, 5.7, 5. , 5.1, 6.8, 7.7, 7.7, 6.4,
        6.3, 5.5, 6.8, 5.4, 5.2, 5.6, 6.5, 7.2, 4.8, 5. , 5.8, 6.7, 5.5,
        6.4, 4.8, 5.2],
       [3.2, 3.2, 2.7, 3. , 2.7, 2.9, 3.4, 3. , 2.3, 2.7, 3. , 3.7, 3.2,
        3. , 3.2, 3. , 3.6, 2.2, 2.8, 2.7, 2.8, 3.4, 2.3, 3.9, 3.4, 3.1,
        3.2, 3. , 3.3, 3.5, 3.1, 2.8, 3. , 3.7, 2.4, 2.9, 2.3, 2.5, 3. ,
        3. , 2.7, 3.3, 3.2, 2.9, 2.6, 3.1, 2.4, 3.2, 3. , 2.9, 3.8, 3.8,
        2.8, 2.7, 2.8, 3.3,

In [ ]:
Y_train

array([2., 1., 1., 1., 2., 0., 0., 1., 1., 2., 0., 0., 1., 2., 1., 1., 0.,
       1., 2., 1., 1., 0., 1., 0., 2., 0., 2., 2., 1., 0., 2., 1., 2., 0.,
       1., 1., 1., 2., 1., 1., 2., 0., 2., 1., 2., 0., 1., 0., 2., 1., 0.,
       2., 2., 1., 2., 2., 1., 0., 2., 0., 1., 1., 0., 2., 0., 1., 0., 1.,
       0., 2., 0., 0., 2., 2., 0., 0., 2., 0., 0., 2., 1., 1., 2., 2., 2.,
       1., 0., 0., 2., 1., 0., 0., 0., 0., 0., 0., 2., 1., 0., 1., 2., 2.,
       2., 1., 2., 0., 1., 0., 0., 1., 2., 2., 0., 0., 2., 1., 1., 2., 0.,
       1.])

In [ ]:
def initial_parameters():
  W1 = np.random.randn(64, 4) - np.sqrt(2./4)
  B1 = np.random.randn(64, 1) - np.sqrt(2./64)
  W2 = np.random.randn(64, 64) - np.sqrt(2./64)
  B2 = np.random.randn(64, 1) - np.sqrt(2./64)
  W3 = np.random.randn(3, 64) - np.sqrt(2./64)
  B3 = np.random.randn(3, 1) - np.sqrt(2./3)
  return W1, B1, W2, B2, W3, B3

In [ ]:
def ReLU(Z1):
  return np.maximum(0, Z1)

In [ ]:
def softmax(Z3):
  Z3 = np.array(Z3)
  Z3 = Z3 - np.max(Z3, axis=0)
  exponent = np.exp(Z3)
  return exponent / np.sum(exponent, axis=0)

In [ ]:
def forward_propagation(W1, B1, W2, B2, W3, B3, X):
  Z1 = np.dot(W1, X) + B1
  A1 = ReLU(Z1)
  Z2 = np.dot(W2, A1) + B2
  A2 = ReLU(Z2)
  Z3 = np.dot(W3, A2) + B3
  A3 = softmax(Z3)
  return Z1, A1, Z2, A2, Z3, A3

In [ ]:
def one_hot(Y):
  Y = Y.astype(int)
  one_hot_Y = np.zeros((Y.size, Y.max() + 1))
  one_hot_Y[np.arange(Y.size), Y] = 1
  one_hot_Y = one_hot_Y.T
  return one_hot_Y

In [ ]:
def derivative_ReLU(Z):
  return Z > 0

In [ ]:
def backward_propagation(W1, B1, W2, B2, W3, B3, Z1, A1, Z2, A2, Z3, A3, X, Y):
  m = Y.size
  one_hot_Y = one_hot(Y)
  dZ3 = A3 - one_hot_Y
  dW3 = 1 / m * np.dot(dZ3, A2.T)
  dB3 = 1 / m * np.sum(dZ3, axis=1, keepdims = True)
  dZ2 = np.dot(W3.T, dZ3) * derivative_ReLU(Z2)
  dW2 = 1 / m * np.dot(dZ2, A1.T)
  dB2 = 1 / m * np.sum(dZ2, axis=1, keepdims = True)
  dZ1 = np.dot(W2.T, dZ2) * derivative_ReLU(Z1)
  dW1 = 1 / m * np.dot(dZ1, X.T)
  dB1 = 1 / m * np.sum(dZ1, axis=1, keepdims = True)
  return dW1, dB1, dW2, dB2, dW3, dB3

In [ ]:
def update_parameters(W1, B1, W2, B2, W3, B3, dW1, dB1, dW2, dB2, dW3, dB3, alpha):
  W1 = W1 - alpha * dW1
  B1 = B1 - alpha * dB1
  W2 = W2 - alpha * dW2
  B2 = B2 - alpha * dB2
  W3 = W3 - alpha * dW3
  B3 = B3 - alpha * dB3
  return W1, B1, W2, B2, W3, B3

In [ ]:
def prediction(A3):
  return np.argmax(A3, axis = 0)

In [ ]:
def get_accuracy(predictions, Y):
  return np.sum(predictions == Y) / Y.size

In [ ]:
def gradient_descent(X, Y, alpha, iterations):
  W1, B1, W2, B2, W3, B3 = initial_parameters()
  for i in range(iterations):
    Z1, A1, Z2, A2, Z3, A3 = forward_propagation(W1, B1, W2, B2, W3, B3, X)
    dW1, dB1, dW2, dB2, dW3, dB3 = backward_propagation(W1, B1, W2, B2, W3, B3, Z1, A1, Z2, A2, Z3, A3, X, Y)
    W1, B1, W2, B2, W3, B3 = update_parameters(W1, B1, W2, B2, W3, B3, dW1, dB1, dW2, dB2, dW3, dB3, alpha)
    if i % 50 == 0:
      predictions = prediction(A3)
      print("Prediction", predictions)
      accuracy = get_accuracy(predictions, Y)
      print("Accuracy", accuracy)
  return W1, B1, W2, B2, W3, B3

In [ ]:
W1, B1, W2, B2, W3, B3 = gradient_descent(X_train, Y_train, 0.01, 500)

Prediction [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1]
Accuracy 0.3333333333333333
Prediction [2 1 2 1 2 0 0 1 1 2 0 0 1 2 1 1 0 1 2 1 1 0 1 0 2 0 2 2 1 0 2 1 2 0 1 1 1
 2 1 1 2 0 2 1 2 0 1 0 2 1 0 2 2 1 2 2 1 0 2 0 1 1 0 2 0 1 0 1 0 2 0 0 2 2
 0 0 2 0 0 2 1 1 2 2 2 1 0 0 2 1 0 0 0 0 0 0 2 1 0 1 2 2 2 1 2 0 1 0 0 1 2
 2 0 0 2 1 1 2 0 1]
Accuracy 0.9916666666666667
Prediction [2 1 2 1 2 0 0 1 1 2 0 0 1 2 1 1 0 1 2 1 1 0 1 0 2 0 2 2 1 0 2 1 2 0 1 1 1
 2 1 1 2 0 2 1 2 0 1 0 2 1 0 2 2 1 2 2 1 0 2 0 1 1 0 2 0 1 0 1 0 2 0 0 2 2
 0 0 2 0 0 2 1 1 2 2 2 1 0 0 2 1 0 0 0 0 0 0 2 1 0 1 2 2 2 1 2 0 1 0 0 1 2
 2 0 0 2 1 1 2 0 1]
Accuracy 0.9916666666666667
Prediction [2 1 2 1 2 0 0 1 1 2 0 0 1 2 1 1 0 1 2 1 1 0 1 0 2 0 2 2 1 0 2 1 2 0 1 1 1
 2 1 1 2 0 2 1 2 0 1 0 2 1 0 2 2 1 2 2 1 0 2 0 1 1 0 2 0 1 0 1